#!/bin/bash

selection="$(dot-desktop | bemenu -i -p 'exec:' --fn 'monospace 16' --tf '#00FF00' --hf '#FFFFFF' --nf '#999999')"
if [ "$selection" != "" ]
then
    command_str="$(DOT_DESKTOP_APP="swaymsg exec" dot-desktop "${selection}")"
    if [ "$command_str" == "" ]
    then
        # No desktop file matched, raw command line
        command_str="${selection}"
    fi

    $command_str
fi

exit 1

