#!/bin/bash

selection="$(dot-desktop | wldash)"
if [ "$selection" != "" ]
then
    command_str="$(DOT_DESKTOP_APP="swaymsg exec" dot-desktop "${selection}")"
    if [ "$command_str" == "" ]
    then
        # No desktop file matched, raw command line
        command_str="${selection}"
    fi

    $command_str
fi

exit 1

